// src/config/universal/sub-atoms/index.ts
// Barrel file - re-exports all sub-atoms

export {
  STRING_CONSTRAINTS,
  STRING_CONSTRAINTS_LONG,
  STRING_CONSTRAINTS_SHORT,
  STRING_CONSTRAINTS_STANDARD,
} from "./string-constraints";

export {
  INTEGER_CONSTRAINTS,
  INTEGER_CONSTRAINTS_PERCENTAGE,
  INTEGER_CONSTRAINTS_POSITIVE,
  INTEGER_CONSTRAINTS_SIGNED,
  INTEGER_CONSTRAINTS_STANDARD,
} from "./integer-constraints";

export {
  FIELD_MARKER_OPTIONAL,
  FIELD_MARKER_PRIMARY,
  FIELD_MARKER_REQUIRED,
  FIELD_MARKER_SYSTEM,
  FIELD_MARKERS,
} from "./field-markers";

export {
  DISPLAY_FORMAT_DATETIME,
  DISPLAY_FORMAT_HIDDEN,
  DISPLAY_FORMAT_NUMBER,
  DISPLAY_FORMAT_TEXT,
  DISPLAY_FORMAT_SELECT,
  DISPLAY_FORMAT_TEXTAREA,
  DISPLAY_FORMAT_TOGGLE,
  DISPLAY_FORMATS,
} from "./display-formats";

export {
  STAT_CATEGORY_ATTRIBUTE,
  STAT_CATEGORY_RESOURCE,
  STAT_CATEGORY_OFFENSIVE,
  STAT_CATEGORY_DEFENSIVE,
  STAT_CATEGORY_UTILITY,
  STAT_CATEGORIES,
} from "./stat-categories";
export type { StatCategory } from "./stat-categories";

export {
  STAT_DATA_TYPE_RAW,
  STAT_DATA_TYPE_PERCENTAGE,
  STAT_DATA_TYPE_MULTIPLIER,
  STAT_DATA_TYPES,
} from "./stat-data-types";
export type { StatDataType } from "./stat-data-types";
