// src/config/universal/sub-atoms/index.ts
// Barrel file - re-exports all sub-atoms

export {
  STRING_CONSTRAINTS,
  STRING_CONSTRAINTS_LONG,
  STRING_CONSTRAINTS_SHORT,
  STRING_CONSTRAINTS_STANDARD,
} from "./string-constraints";

export {
  INTEGER_CONSTRAINTS,
  INTEGER_CONSTRAINTS_PERCENTAGE,
  INTEGER_CONSTRAINTS_POSITIVE,
  INTEGER_CONSTRAINTS_STANDARD,
} from "./integer-constraints";

export {
  FIELD_MARKER_OPTIONAL,
  FIELD_MARKER_PRIMARY,
  FIELD_MARKER_REQUIRED,
  FIELD_MARKER_SYSTEM,
  FIELD_MARKERS,
} from "./field-markers";

export {
  DISPLAY_FORMAT_DATETIME,
  DISPLAY_FORMAT_HIDDEN,
  DISPLAY_FORMAT_NUMBER,
  DISPLAY_FORMAT_TEXT,
  DISPLAY_FORMAT_TEXTAREA,
  DISPLAY_FORMAT_TOGGLE,
  DISPLAY_FORMATS,
} from "./display-formats";
